### PR TITLE
Implements interface inheritance in Djinni. 

### PR DESCRIPTION
**Pull request by fostah**
Includes:

* New 'interface extends' syntax support.
* Code generation for interfaces that extend other interfaces.
* Proper object conversion from one language to another. No type slicing when references as a super interface.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@fostah, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/) and update the thread so we can consider merging your code.

**Comment by fostah** [comment]
Sorry, this was meant for our fork. Not sure how I ended up here.

**Comment by artwyman** [comment]
I like the concept of the feature, though.  It's been on our wish list for a while, so if you want to someday turn this into something you're willing to upstream, I'd be happy to review it.

**Comment by fostah** [comment]
Thanks. I'm glad you're interested in it as I definitely want to push it upstream at some point.

**Pull request closed without merging**
