### PR TITLE
Generate interfaces in Java when possible

### PR DESCRIPTION
**Pull request by mrdomino**
If the djinni interface doesn't contain constants or static members, then it
can be represented as an interface (not abstract class) in Java.

### CODE REVIEW

**Comment by mrdomino** [comment]
Any feedback on this? It makes it a lot easier to use Djinni-generated classes in Android apps, e.g. by implementing a listener interface while still extending Activity to get easy access to runOnUiThread.

**Comment by mrdomino** [comment]
Aha. It seems that this change may violate some assumptions of the JNI support code. When we implement multiple djinni interfaces at once, our app crashes with jniExceptionCheck, and we see "JNI WARNING: DeleteLocalRef(0x421d2948) failed to find entry" right beforehand.

Is this a known issue?

**Comment by Bennyyyy** [comment]
+1

**Comment by mrdomino** [comment]
Bump.

**Comment by mknejp** [comment]
I do agree that `+j`interfaces should create an `interface`. Constants aren't a problem (an `interface` can have `public static final` member values), however the Objective-C generator does support static methods (though I haven't see a use for it yet and it won't be allowed for `+j +o`). However, making the creation of `class` versus `interface` conditional just means a lot of code can break simply because someone added a static method somewhere in a Djinni file.

> Aha. It seems that this change may violate some assumptions of the JNI support code. When we implement multiple djinni interfaces at once, our app crashes with jniExceptionCheck, and we see "JNI WARNING: DeleteLocalRef(0x421d2948) failed to find entry" right beforehand.

It would help to recreate your situation in a test as a starting point, even if you can't find a fix.

**Comment by mrdomino** [comment]
I actually am having a hard time reproducing that issue.

**Comment by artwyman** [comment]
This is clever, but I share @mknejp's concerns about the automatic nature of it causing easy build breakages.  In its current state, I think the feature should be optional, controlled by a command-line switch.

There might be a better alternative if we can raise the requirement to Java 8, which will be supported by Android officially soon.  That will allow static methods on interfaces.  That just leaves the static inner class for the auto-generated CppProxy as a blocking factor, but I think that could be moved out into a separate Java class (package-private) without it being a big deal.  I think something like that, which would allow all Djinni interfaces to be Java interfaces would be a better feature in the long term.

**Comment by itsff** [comment]
@artwyman For the time being, could we at least generate Java interfaces for cases where no static methods are present? As you suggested, the CppProxy class could be implemented (via convention) as a separate package private class. This would really help for cases where a Java class is supposed to implement many listeners for callbacks.

**Comment by artwyman** [comment]
@itsff that's what this original PR proposed to do, and I think it's a reasonable feature.  The open issues are making it optional behavior (so that existing code doesn't break unnecessarily because someone adds/removes a static method), and figuring out if the proxy cache really has problems with this scenario (it's designed not to, since the same can come up in Objective-C with protocols, but it hasn't been tested).

**Comment by artwyman** [comment]
Supplanted by #288

**Pull request closed without merging**
