### PR TITLE
fixed `isInterface` function, when given Interface is MExtern (issue 401)

### PR DESCRIPTION
**Pull request by ctin**

### CODE REVIEW

**Comment by ctin** [comment]
https://github.com/dropbox/djinni/issues/401

**Comment by xianwen** [comment]
Hi, @ctin:
I noticed you haven't signed the CLA yet, could you please sign it here: https://opensource.dropbox.com/cla/
Thanks a lot!

**Comment by ctin** [comment]
Hi, @xianwen 
Done.

**Comment by xianwen** [comment]
Hi ctin:

Generally LGTM.
Could you please add a test case in the example test suite, so that we can verify the fix and prevent  from regression in the future?

Thanks!

**Comment by prsolucoes** [comment]
Hi @ctin,

Can you add a test to merge it?

Thanks.

**Comment by ctin** [comment]
To correctly add test for my merge request I need:
1) create yaml file with an interface:
```extern_test_interface = interface +c +j +o {
}```
2) create djinni file with a record, which are using that interface:
```@extern "extern_test_interface"

test_extern_interface_record = record {
extern_test_interface = optional<extern_test_interface>;
}```

in current master record above will have line:
```std::experimental::optional<std::shared_ptr<::extern_test_interface>> extern_test_interface;```
but with my fix will be generated line:
```std::shared_ptr<::extern_test_interface> extern_test_interface;```

I have next questions:
1) where I can place my yaml file?
2) how I can check that correct type is generated?
3) how to add this check to java and objc tests?

**Comment by ctin** [comment]
@xianwen please review

**Pull request merged**
