### PR TITLE
Fix error when building with VS2015

### PR DESCRIPTION
**Pull request by menuet**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@menuet, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by artwyman** [comment]
@menuet This looks fine to merge as soon as the CLA is signed.  Thanks!

**Comment by menuet** [comment]
OK Thanks.

Actually, I would like to propose a cleaner fix for VS2015, so please don't merge my first request.
I will close it.
I will submit a new request soon, after having signed your CLA.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@menuet, thanks for signing the CLA!

**Pull request closed without merging**
