### PR TITLE
Inheritance and parcelable support

### PR DESCRIPTION
**Pull request by konovalov-aleks**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@konovalov-aleks, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by Avenza** [comment]
Looks like an interesting MR. Why closing it? But it seems that it is not finished, without adding the necessary changes to ObjC++?

**Comment by konovalov-aleks** [comment]
Yes, it is not finished. I created a pull request by mistake. In the future
I plan to finish ObjC++ support, and then I'll create a pull request

2016-07-11 23:09 GMT+03:00 Avenza System Inc <notifications@github.com>:

**Comment by artwyman** [comment]
Looks like some good features, so I look forward to the final version.  I have some suggestion to ease the review and merge process.  Firstly it looks like there might be several independent features here, which would be easiest to review and integrate separately.  Secondly please add tests to the test-suite to demonstrate and validate your new features.

**Comment by Avenza** [comment]
@konovalov-aleks looking forward to it!! It may not be a bad idea to break the work into chunks though so that it is easier to review. Things like `cppUseWideStrings` can definitely be merged in earlier.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@konovalov-aleks, thanks for signing the CLA!

**Pull request closed without merging**
