### PR TITLE
Work-arounds to make Djinni build on Windows with MSVC >=2013

### PR DESCRIPTION
**Pull request by forderud**
Changes necessary to make Djinni build successfully on Windows with Microsoft Visual Studio 2013 and newer.

### CODE REVIEW

**Comment by forderud** [comment]
Gentle reminder.

**Comment by forderud** [comment]
Gentle reminder.

**Comment by j4cbo** [comment]
Sorry for the long delay here. Can you fill out our CLA at https://opensource.dropbox.com/cla/ and then I can merge these?

**Comment by forderud** [comment]
Done.

**Pull request merged**
