### PR TITLE
Improve IDEA plugin

### PR DESCRIPTION
**Pull request by ice1000**
Added:

+ brace matcher
+ highlight for keywords

### CODE REVIEW

**Comment by xianwen** [comment]
Hi, @ice1000:
I noticed you haven't signed the CLA yet, could you please sign it here: https://opensource.dropbox.com/cla/
Thanks a lot!

**Comment by ice1000** [comment]
@xianwen Thanks for notifying! I've just signed it.

**Comment by ice1000** [comment]
Ooops, I've unexpectedly removed some copyrights. Will revert them.

**Comment by ice1000** [comment]
Hi @xianwen is there anything blocking this pr to be merged?
I didn't make any change in code style / comments and tried my best to fit the original coding convention.

**Comment by ice1000** [comment]
Also I've found a commonly thrown exception:

```
Argument for @NotNull parameter 'visibilityContext' of com/dropbox/djinni/ideaplugin/DjinniUtil.findAllExternalFiles must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'visibilityContext' of com/dropbox/djinni/ideaplugin/DjinniUtil.findAllExternalFiles must not be null
	at com.dropbox.djinni.ideaplugin.DjinniUtil.findAllExternalFiles(DjinniUtil.java)
	at com.dropbox.djinni.ideaplugin.DjinniUtil.findAllExternalTypes(DjinniUtil.java:129)
	at com.dropbox.djinni.ideaplugin.DjinniChooseByNameContributor.getNames(DjinniChooseByNameContributor.java:43)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:98)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:82)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:927)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
```

Fixed in d3db9fe

**Comment by ice1000** [comment]
[intellij-plugin.zip](https://github.com/dropbox/djinni/files/2029364/intellij-plugin.zip)

Here's a jar version of the plugin containing the newest changes, and it's renamed to `.zip` for github uploading convenience.

**Pull request merged**
